version: '3.8'

services:

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file: .env
    environment:
      - MINIO_HOST_NAME=http://18.134.244.47/
      - MINIO_BROWSER_REDIRECT_URL=http://18.134.244.47/minio/ui
    volumes:
      - minio_data:/data
    networks:
      - backend
    deploy:
      replicas: 1
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    env_file: .env
    environment:
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_RELATIVE_PATH=/keycloak
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
    networks:
      - backend
    deploy:
      replicas: 1

volumes:
  elastic_data:
  minio_data:

networks:
  backend:
    external: true
