version: '3.8'

services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    deploy:
      placement:
        constraints:
          - node.hostname == manager1

networks:
  backend:
    external: true

